<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/MasterPage.master" AutoEventWireup="true" CodeFile="Item_Grpmast.aspx.cs" Inherits="Admin_Item_Grpmast" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:Panel ID="pnlCategory" runat="server"  Width="300px" 
    style="background-color:Window; margin-left:400px; margin-top:100px;" ForeColor="#000099">

    <asp:GridView ID="dgvItemCategory" runat="server" DataKeyNames="Category_Id" 
        DataSourceID="SqlDataSource1" AutoGenerateSelectButton="true" Width="300px"
        style="text-align: center; background-color:Window;">
    </asp:GridView>
    </asp:Panel>

    <br />

    <asp:Panel ID="pnlgroup" runat="server" Width="500px"
    style="background-color:Window; margin-left:350px; " ForeColor="#000099">
    
    <%--<asp:DetailsView ID="DetailsView1" 	runat="server" AllowPaging="True" 
        AutoGenerateEditButton="True" AutoGenerateInsertButton="True" 
        AutoGenerateDeleteButton="True"
        DataSourceID="SqlDataSource2"  DataKeyNames="GrpCode" Width="500px"
        style="text-align: left;background-color:Window;">
    </asp:DetailsView>--%>

    <asp:GridView ID="dgvGroup" runat="server" DataKeyNames="GrpCode" 
        DataSourceID="SqlDataSource2" AllowPaging="True" 
        AutoGenerateEditButton="True" 
        AutoGenerateDeleteButton="True" Width="300px"
        style="text-align: center; background-color:Window;">
    </asp:GridView>


    </asp:Panel>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:COSConnectionString %>" 
        SelectCommand="SELECT * FROM [Item_Category]">
    </asp:SqlDataSource> 

    <asp:SqlDataSource ID="SqlDataSource2" 						
ConnectionString="<%$ConnectionStrings:COSConnectionString%>"
SelectCommand="SELECT GrpCode,GrpName FROM Item_GrpMast Where Category_Id=@Code" 
UpdateCommand="Update Item_GrpMast SET GrpName=@GrpName Where GrpCode=@GrpCode" 
DeleteCommand="Delete from Item_GrpMast where GrpCode=@GrpCode" 
InsertCommand="Insert into Item_GrpMast(Grpname,Category_Id) values(@GrpName,@Code)" 
runat="server">

<SelectParameters>
<asp:ControlParameter Name="Code" ControlID="dgvItemCategory"/>
</SelectParameters>

<InsertParameters>
<asp:ControlParameter Name="Code" ControlID="dgvItemCategory"/>
</InsertParameters>

<DeleteParameters>
<asp:ControlParameter Name="Code" ControlID="dgvGroup"/>
</DeleteParameters>

</asp:SqlDataSource>


</asp:Content>

